---
# tasks file for my_new_role
- name: Molecule Installation!
  ansible.builtin.debug:
    msg: Bienvenue dans cette installation Molecule version {{version}}

- name: Installation des outils
  include_tasks: tools.yml

- name: Installation de l'application node
  include_tasks: node.yml

- name: Installation du serveur nginx
  include_tasks: nginx.yml
