---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ubuntu
    image: ubuntu:latest
    privileged: true
    published_ports:
      - 80:80
      - 3002:3002
      - 3000:3000
provisioner:
  name: ansible
verifier:
  name: ansible
